// LOCALES
export const LOCALES__SET_LANGUAGE = 'LOCALES::SET_LANGUAGE'

// COUNTER
export const COUNTER__INCREMENT = 'COUNTER::INCREMENT'
export const COUNTER__DECREMENT = 'COUNTER::DECREMENT'
export const COUNTER__RESET = 'COUNTER::RESET'
